# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/RTL/Basys-3-Master.xdc

# Block Designs: bd/axi_test_1/axi_test_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1 || ORIG_REF_NAME==axi_test_1} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_axi_slave_fsm_0_0/axi_test_1_axi_slave_fsm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_axi_slave_fsm_0_0 || ORIG_REF_NAME==axi_test_1_axi_slave_fsm_0_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_clk_wiz_0_0 || ORIG_REF_NAME==axi_test_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_microblaze_0_0/axi_test_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_microblaze_0_0 || ORIG_REF_NAME==axi_test_1_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_dlmb_v10_0/axi_test_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_dlmb_v10_0 || ORIG_REF_NAME==axi_test_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_ilmb_v10_0/axi_test_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_ilmb_v10_0 || ORIG_REF_NAME==axi_test_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_dlmb_bram_if_cntlr_0/axi_test_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_test_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_ilmb_bram_if_cntlr_0/axi_test_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_test_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_lmb_bram_0/axi_test_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_lmb_bram_0 || ORIG_REF_NAME==axi_test_1_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_mdm_1_0/axi_test_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_mdm_1_0 || ORIG_REF_NAME==axi_test_1_mdm_1_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_rst_clk_wiz_0_100M_0/axi_test_1_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==axi_test_1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_axi_master_fsm_0_0/axi_test_1_axi_master_fsm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_axi_master_fsm_0_0 || ORIG_REF_NAME==axi_test_1_axi_master_fsm_0_0} -quiet] -quiet

# IP: bd/axi_test_1/ip/axi_test_1_bfm_0_0/axi_test_1_bfm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_test_1_bfm_0_0 || ORIG_REF_NAME==axi_test_1_bfm_0_0} -quiet] -quiet

# XDC: bd/axi_test_1/axi_test_1_ooc.xdc
