# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/RTL/Basys-3-Master.xdc

# Block Designs: bd/micro_blaze_AMBA_BUS/micro_blaze_AMBA_BUS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS || ORIG_REF_NAME==micro_blaze_AMBA_BUS} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_clk_wiz_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_clk_wiz_0_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_0/micro_blaze_AMBA_BUS_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_microblaze_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_microblaze_0_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_dlmb_v10_0/micro_blaze_AMBA_BUS_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_dlmb_v10_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_dlmb_v10_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_ilmb_v10_0/micro_blaze_AMBA_BUS_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_ilmb_v10_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_ilmb_v10_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_dlmb_bram_if_cntlr_0/micro_blaze_AMBA_BUS_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_ilmb_bram_if_cntlr_0/micro_blaze_AMBA_BUS_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_lmb_bram_0/micro_blaze_AMBA_BUS_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_lmb_bram_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_lmb_bram_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_mdm_1_0/micro_blaze_AMBA_BUS_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_mdm_1_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_mdm_1_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_axi_periph_0/micro_blaze_AMBA_BUS_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_microblaze_0_axi_periph_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_xbar_0/micro_blaze_AMBA_BUS_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_xbar_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_xbar_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_axi_uartlite_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_myip_test_axi_1_0_0/micro_blaze_AMBA_BUS_myip_test_axi_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_myip_test_axi_1_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_myip_test_axi_1_0_0} -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_clk_wiz_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_clk_wiz_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0_ooc.xdc

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_0/micro_blaze_AMBA_BUS_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_microblaze_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_0/micro_blaze_AMBA_BUS_microblaze_0_0_ooc_debug.xdc

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_dlmb_v10_0/micro_blaze_AMBA_BUS_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_dlmb_v10_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_ilmb_v10_0/micro_blaze_AMBA_BUS_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_ilmb_v10_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_lmb_bram_0/micro_blaze_AMBA_BUS_lmb_bram_0_ooc.xdc

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_mdm_1_0/micro_blaze_AMBA_BUS_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_mdm_1_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_mdm_1_0/micro_blaze_AMBA_BUS_mdm_1_0_ooc_trace.xdc

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_axi_uartlite_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0_ooc.xdc

# XDC: bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_blaze_AMBA_BUS_axi_uartlite_0_0 || ORIG_REF_NAME==micro_blaze_AMBA_BUS_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_blaze_AMBA_BUS/micro_blaze_AMBA_BUS_ooc.xdc
