# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.cache/wt [current_project]
set_property parent.project_path C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/sunda/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/github/amba_bus/ip_repo/myip_input_sw_output_led_1.0
  c:/github/amba_bus/ip_repo/myip_axi_test_led_1.0
  c:/github/amba_bus/ip_repo/myip_axi_led_on_off_1.0
  c:/github/amba_bus/ip_repo/myip_axi_interface_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/hdl/micro_blaze_AMBA_BUS_wrapper.v
add_files C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/micro_blaze_AMBA_BUS.bd
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_clk_wiz_0_0/micro_blaze_AMBA_BUS_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_0/micro_blaze_AMBA_BUS_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_0/micro_blaze_AMBA_BUS_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_dlmb_v10_0/micro_blaze_AMBA_BUS_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_ilmb_v10_0/micro_blaze_AMBA_BUS_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_lmb_bram_0/micro_blaze_AMBA_BUS_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_mdm_1_0/micro_blaze_AMBA_BUS_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_mdm_1_0/micro_blaze_AMBA_BUS_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0/micro_blaze_AMBA_BUS_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_axi_uartlite_0_0/micro_blaze_AMBA_BUS_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/micro_blaze_AMBA_BUS_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/micro_blaze_AMBA_BUS/ip/micro_blaze_AMBA_BUS_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/constrs_1/imports/RTL/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/constrs_1/imports/RTL/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top micro_blaze_AMBA_BUS_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef micro_blaze_AMBA_BUS_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file micro_blaze_AMBA_BUS_wrapper_utilization_synth.rpt -pb micro_blaze_AMBA_BUS_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
