# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0.xci
# IP: The module: 'axi_test_1_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_test_1_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_test_1_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_test_1_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0.xci
# IP: The module: 'axi_test_1_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_test_1_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_test_1_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/github/amba_bus/soc_AMBA_BUS/soc_AMBA_BUS.srcs/sources_1/bd/axi_test_1/ip/axi_test_1_clk_wiz_0_0/axi_test_1_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_test_1_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
