@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Oct 07 15:11:56 +0900 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_axi_simulation_behav -key {Behavioral:sim_1:Functional:tb_axi_simulation} -tclbatch tb_axi_simulation.tcl -protoinst "protoinst_files/micro_blaze_AMBA_BUS.protoinst" -log simulate.log"
call xsim  tb_axi_simulation_behav -key {Behavioral:sim_1:Functional:tb_axi_simulation} -tclbatch tb_axi_simulation.tcl -protoinst "protoinst_files/micro_blaze_AMBA_BUS.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
